### ISSUE TITLE
Issue with prefix? The plugin want to update.

### ISSUE THREAD

**Issue by madebyaris** [syntatis/howdy#6]
![image](https://github.com/user-attachments/assets/8618bb81-0935-4736-8470-a498acdf10c0)

it's fresh install from this command:
`composer create-project syntatis/howdy -s dev`

And it was weird because I believe the prefix isn't owned by anyone.

<img width="694" alt="image" src="https://github.com/user-attachments/assets/e10db732-daaf-4ddd-96d8-90ced5e11c2c">

**Comment by tfirdaus** [comment]
@madebyaris Thanks for the report. 
That's kind of weird that WordPress.org has reported there is an update, considering that this is a new plugin with a fresh ID.
Have you tried to check if the actual prefix or plugin ID available in WordPress.org?

**Comment by madebyaris** [comment]
I noticed that the issue isn't from your, I created a new plugin (under the same current WP) with a different prefix, and it's still occure.

And when I fresh install it + reset Opcache, it work fine now.
